[package]
name = "axum-in-process"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.10", features = ["macros"] }
notify = "5.1.0"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread", "sync", "rt"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["fs"] }
tower-livereload = { path = "../.." }
