[package]
authors = ["Leo Gaskin <leo.gaskin@le0.gs>"]
categories = ["development-tools", "web-programming::http-server"]
description = "A development server with live-reload capabilities."
edition = "2021"
homepage = "https://github.com/leotaku/tower-livereload/examples/livehttpd"
keywords = ["front-end", "development", "tool", "server", "http"]
license = "MIT OR Apache-2.0"
name = "livehttpd"
readme = "README.md"
repository = "https://github.com/leotaku/tower-livereload"
version = "1.0.5-wip"

[dependencies]
axum = "0.6.18"
clap = { version = "4.3.11", features = ["derive"] }
notify = "6.0.1"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread", "sync", "rt"] }
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["fs", "set-header"] }
tower-livereload = { version = "0.8.1-wip", path = "../.." }
tracing-subscriber = "0.3.17"
